// <auto-generated />
namespace AHelpingHand.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addingNewView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingNewView));
        
        string IMigrationMetadata.Id
        {
            get { return "202009092014375_addingNewView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
